#!/bin/sh
#BASEDIR=$(dirname $0)
BASEDIR=/Users/nlarusstone/Documents/Research/thesis/Dissertate-Harvard-LaTeX
echo $BASEDIR
cd $BASEDIR
#cd ..

# Build the dissertation.
xelatex dissertation
bibtex dissertation
xelatex dissertation
xelatex dissertation

# Hide the log.
mv "dissertation.log" ".logged"

